AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for React App Hosting with S3 and CloudFront

Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${ReactAppBucket}/*

  ReactAppCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: ReactAppOrigin
            DomainName: !GetAtt ReactAppBucket.RegionalDomainName
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: ReactAppOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100

Outputs:
  WebsiteURL:
    Value: !GetAtt ReactAppBucket.WebsiteURL
    Description: URL of the static website

  CloudFrontURL:
    Value: !GetAtt ReactAppCloudFront.DomainName
    Description: CloudFront Distribution URL
